# Generated by Django 4.1.4 on 2022-12-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=6)),
                ('comment', models.CharField(max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
