# Generated by Django 4.1.4 on 2022-12-21 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_author_alter_ticket_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 21)),
        ),
    ]
