# Generated by Django 4.1.4 on 2022-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='evidence',
            field=models.ImageField(default='null', height_field=400, upload_to='images', width_field=400),
            preserve_default=False,
        ),
    ]
