# Generated by Django 4.1.4 on 2022-12-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='evidence',
            field=models.ImageField(default='https://oncall258.com/wp-content/uploads/2015/03/iStock_000054981982_Small.jpg', upload_to='images'),
        ),
    ]
