# Generated by Django 4.1.4 on 2022-12-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_ticket_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(default='Finance', max_length=80),
        ),
        migrations.AddField(
            model_name='ticket',
            name='manager',
            field=models.CharField(default='Sam Adams', max_length=80),
        ),
    ]
